import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Layout from "@/components/admin/Layout";
import NextTopLoader from "nextjs-toploader";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ecommerce | پنل مدیریت",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirmatn.className} dark:bg-slate-700 dark:text-white`}
      >
        <NextTopLoader showSpinner={false} />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
