import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Layout from "@/components/home/Layout";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ecommerce | صفحه اصلی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirmatn.className}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
